name: notat-web-CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'notat-web/**'
      
  pull_request:
    branches: [ master ]
    paths: 
      - 'notat-web/**'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0

      - name: npm install, validate, test and build
        working-directory: notat-web
        run: |
          npm install
          npm run validate
          npm run test
          npm run build        
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: teodoran
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: teodoran/notes-app/notat-web
          path: notat-web
          tag_with_sha: true
          tags: latest
          push: ${{github.ref == 'refs/heads/master'}}
